services:
  # 1. MQTT Broker
  broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck", "-W", "3"]
      interval: 5s
      timeout: 10s
      retries: 5

  # 2. Django Web Server (Dashboard)
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app  # Mounts source code & DB so changes persist to host
    ports:
      - "8000:8000"
    depends_on:
      broker:
        condition: service_healthy

  # 3. Middleware (The "Worker")
  middleware:
    build: .
    # connect to the 'broker' service defined above
    command: python manage.py runmiddleware --host broker --port 1883
    volumes:
      - .:/app  # MUST match web volume to see the same db.sqlite3
    depends_on:
      broker:
        condition: service_healthy
      web:
        condition: service_started
    restart: on-failure
